# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "superqx"
repo_name: "arxiv_integrability"
show_authors: False
show_links: False
show_badge: False
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/int-arxiv-daily.json'
json_gitpage_path: './docs/int-arxiv-daily-web.json'
json_wechat_path: './docs/int-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Integrable system": 
        filters: ["integrable system", "integrable model", "classical integrability", "quantum integrability"]
    "Exact solution":
        filters: ["exact solution", "exactly solvable", "exactly solvable models"]
    "Conserved charges":
        filters: ["infinite conserved quantities","infinite integrals of motion", "lax pair", "Lax formulation", "infinite commuting charges"]
    "Yang-Baxter equation":
        filters: ["Yang-Baxter integrability", "Reflection equation", "Boundary Yang-Baxter equation"]
    "Bethe ansatz":
        filters: ["algebraic Bethe ansatz", "coordinate Bethe ansatz", "thermodynamic Bethe ansatz", "analytical Bethe ansatz"]
    "2d integrable model":
        filters: ["sine-Gordon model", "Liouville field theory", "Bullough-Dodd model", "Korteweg-de vries equation"]
    "quantum integrable field theory":
        filters: ["integrable QFT", "long-range deformation"]
    "spin chain":
        filters: ["integrable spin chain", "quantum inverse scattering method", "Heisenberg spin chain", "Hubbard model", "Kondo model", "quasilocal conserved charges", "quasilocal charges"]
    "Non-equilibrium":
        filters: ["Eigenstate thermalization hypothesis", "quantum quench"]

