title: Integrability Arxiv Daily
description: Automatically Update integrability Papers Daily using Github Actions
show_downloads: false

# github:
#  zip_url: https://github.com/superqx/arxiv_integrability
#  another_url: https://github.com/superqx/arxiv_integrability

## add remote theme
remote_theme: jekyll/minima@v2.5.1


plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag

# Defaults to apply front matter to specific pages

defaults:

  - scope:
    path: ""       # empty string means the root (all pages)
    type: "pages"  # applies to pages (not posts)
    values:
      layout: default
      title: Integrability Arxiv Daily
